### ISSUE TITLE
7 phenopackets did not run as they have this type of error.

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/LIRICAL#395]
7 phenopackets did not run as they have this type of error. I am guessing old terms that don’t get converted?

Exception in thread "main" java.lang.IllegalArgumentException: no such vertex in graph: HP:0007739

at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)

at org.jgrapht.graph.AbstractBaseGraph.outgoingEdgesOf(AbstractBaseGraph.java:497)

at org.monarchinitiative.phenol.ontology.algo.OntologyAlgorithm.getParentTerms(OntologyAlgorithm.java:173)

at org.monarchinitiative.lirical.likelihoodratio.InducedDiseaseGraph.getClosestAncestor(InducedDiseaseGraph.java:115)

at org.monarchinitiative.lirical.likelihoodratio.PhenotypeLikelihoodRatio.getLikelihoodRatio(PhenotypeLikelihoodRatio.java:118)

at org.monarchinitiative.lirical.likelihoodratio.CaseEvaluator.observedPhenotypesLikelihoodRatios(CaseEvaluator.java:149)

at org.monarchinitiative.lirical.likelihoodratio.CaseEvaluator.evaluateDisease(CaseEvaluator.java:318)

at org.monarchinitiative.lirical.likelihoodratio.CaseEvaluator.phenoGenoEvaluation(CaseEvaluator.java:419)

at org.monarchinitiative.lirical.likelihoodratio.CaseEvaluator.evaluate(CaseEvaluator.java:440)

at org.monarchinitiative.lirical.cmd.PhenopacketCommand.run(PhenopacketCommand.java:137)

at org.monarchinitiative.lirical.Lirical.main(Lirical.java:147)

**Comment by pnrobinson** [comment]
Added code to catch errors like this and report them in the HTML output
