### ISSUE TITLE
Error with the input from Deepvariant pipeline

### ISSUE THREAD

**Issue by genmaibutter** [TheJacksonLaboratory/LIRICAL#585]
Hi, I have error with the input form the Deepvariant pipeline.

java -Xms4g -Xmx4g -jar /data/users/test/apps/LIRICAL/LIRICAL.jar yaml -y deepvariant_LIRICAL_singleton.yml
**java.lang.NullPointerException**
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:105)
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:286)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:398)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:335)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:294)
	at org.monarchinitiative.lirical.analysis.Vcf2GenotypeMap.vcf2genotypeMap(Vcf2GenotypeMap.java:192)
	at org.monarchinitiative.lirical.configuration.LiricalFactory.getGene2GenotypeMap(LiricalFactory.java:560)
	at org.monarchinitiative.lirical.configuration.LiricalFactory.getGene2GenotypeMap(LiricalFactory.java:547)
	at org.monarchinitiative.lirical.cmd.YamlCommand.runVcf(YamlCommand.java:107)
	at org.monarchinitiative.lirical.cmd.YamlCommand.call(YamlCommand.java:176)
	at org.monarchinitiative.lirical.cmd.YamlCommand.call(YamlCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.monarchinitiative.lirical.Lirical.main(Lirical.java:39)

Do you have any recommendation for me ? Anyone have this experience before?

**Comment by ielis** [comment]
Hi @genmaibutter sorry for a long delay, we've been working on upgrades of the code and the docs and we just made a new release.
Can you please see if the error still persists after upgrading to the [latest release](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.0-RC2)? Please see the [revised documentation](https://thejacksonlaboratory.github.io/LIRICAL/latest) and new [YAML file format](https://thejacksonlaboratory.github.io/LIRICAL/latest/yaml.html#rstyaml).

If the problems persist, can you please share LIRICAL log and the offending variant line?

Thanks & cheers,
Daniel
