### ISSUE TITLE
Phenopackets v2 support

### ISSUE THREAD

**Issue by yaseminbridges** [TheJacksonLaboratory/LIRICAL#597]
Hello,

I wondered if there would be support for phenopackets v2. Currently when I try and run LIRICAL with a v2 phenopacket I get this error:

```
15:42:45.517 [main] WARN  o.m.l.i.a.PhenopacketV2Importer - There are 1 genomic interpretations in the phenopacket, but the variant parsing is currently not implemented.
java.lang.IllegalArgumentException: Missing scheme
	at java.base/java.nio.file.Path.of(Path.java:199)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.monarchinitiative.lirical.io.analysis.PhenopacketV2Importer.read(PhenopacketV2Importer.java:99)
	at org.monarchinitiative.lirical.cli.cmd.PhenopacketCommand.prepareAnalysisData(PhenopacketCommand.java:62)
	at org.monarchinitiative.lirical.cli.cmd.AbstractPrioritizeCommand.call(AbstractPrioritizeCommand.java:81)
	at org.monarchinitiative.lirical.cli.cmd.PhenopacketCommand.call(PhenopacketCommand.java:27)
	at org.monarchinitiative.lirical.cli.cmd.AbstractPrioritizeCommand.call(AbstractPrioritizeCommand.java:28)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.monarchinitiative.lirical.cli.Main.main(Main.java:43)
```

If not it may be useful if you could make the input check for phenopackets less strict.

Thanks,

Yasemin

**Comment by ielis** [comment]
Hi @yaseminbridges we made a lot of updates to the code base and we have a [new release](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.0-RC2) with [updated docs](https://thejacksonlaboratory.github.io/LIRICAL/latest) for setup and running. The updates include support for both v1 and v2 phenopackets.

I believe, however, that the issue may be caused by an invalid URI in your input phenopacket since the stack trace indicates that the error originates in `java.base/java.nio.file.Path.of(Path.java:199)`.

Can you please re-test with the new version and let me know if the issue persists?

Thanks,
Daniel

**Comment by yaseminbridges** [comment]
Hi @ielis, yes you are completely right, it was due to an invalid URI in the input phenopacket! I didn't realise this was the issue as I was providing the path to the VCF in the CLI so I thought it would get ignored in the phenopacket.

Thanks,
Yasemin
