### ISSUE TITLE
Database download error!

### ISSUE THREAD

**Issue by MiladEidi** [TheJacksonLaboratory/LIRICAL#660]
Hi dear developers,
when I try to download lirical's database it returns these:

(base) milad@DESKTOP-VI9DTD8:/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2$ java -jar lirical-cli-2.0.2.jar D
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]

  _     ___ ____  ___ ____    _    _
 | |   |_ _|  _ \|_ _/ ___|  / \  | |
 | |    | || |_) || | |     / _ \ | |
 | |___ | ||  _ < | | |___ / ___ \| |___
 |_____|___|_| \_\___\____/_/   \_\_____|

LIkelihood Ratio Interpretation of Clinical AbnormaLities
                                    :: v2.0.2 ::

08:44:11.712 [main] INFO  o.m.lirical.cli.cmd.DownloadCommand - Downloading data to /mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data
08:44:12.221 [main] INFO  o.m.biodownload.BioDownloaderBuilder - The builder validation is successful.
08:44:12.222 [main] INFO  o.m.biodownload.BioDownloaderImpl - Cowardly refusing to download "hp.json" since we found it at "/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data/hp.json"
08:44:12.223 [main] INFO  o.m.biodownload.BioDownloaderImpl - Cowardly refusing to download "phenotype.hpoa" since we found it at "/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data/phenotype.hpoa"
08:44:12.223 [main] INFO  o.m.biodownload.BioDownloaderImpl - Cowardly refusing to download "hgnc_complete_set.txt" since we found it at "/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data/hgnc_complete_set.txt"
08:44:12.223 [main] INFO  o.m.biodownload.BioDownloaderImpl - Cowardly refusing to download "mim2gene_medgen" since we found it at "/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data/mim2gene_medgen"
08:44:12.912 [main] ERROR o.m.biodownload.FileDownloader - Failed to downloaded file from storage.googleapis.com
java.io.IOException: Server returned HTTP response code: 403 for URL: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2044)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2039)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2038)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1605)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.monarchinitiative.biodownload.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:106)
        at org.monarchinitiative.biodownload.FileDownloader.copyURLToFile(FileDownloader.java:86)
        at org.monarchinitiative.biodownload.BioDownloaderImpl.downloadFileIfNeeded(BioDownloaderImpl.java:69)
        at org.monarchinitiative.biodownload.BioDownloaderImpl.download(BioDownloaderImpl.java:49)
        at org.monarchinitiative.lirical.cli.cmd.DownloadCommand.execute(DownloadCommand.java:57)
        at org.monarchinitiative.lirical.cli.cmd.BaseCommand.call(BaseCommand.java:31)
        at org.monarchinitiative.lirical.cli.cmd.DownloadCommand.call(DownloadCommand.java:21)
        at org.monarchinitiative.lirical.cli.cmd.BaseCommand.call(BaseCommand.java:18)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.monarchinitiative.lirical.cli.Main.main(Main.java:46)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at org.monarchinitiative.biodownload.FileDownloader.connect(FileDownloader.java:149)
        at org.monarchinitiative.biodownload.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:104)
        ... 16 common frames omitted
08:44:12.920 [main] ERROR o.m.biodownload.BioDownloaderImpl - Error downloading "hg19_ucsc.ser" from "https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser": ERROR: Problem downloading file: Server returned HTTP response code: 403 for URL: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
08:44:12.920 [main] ERROR o.m.lirical.cli.cmd.DownloadCommand - Error: ERROR: Problem downloading file: Server returned HTTP response code: 403 for URL: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
org.monarchinitiative.biodownload.FileDownloadException: ERROR: Problem downloading file: Server returned HTTP response code: 403 for URL: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
        at org.monarchinitiative.biodownload.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:136)
        at org.monarchinitiative.biodownload.FileDownloader.copyURLToFile(FileDownloader.java:86)
        at org.monarchinitiative.biodownload.BioDownloaderImpl.downloadFileIfNeeded(BioDownloaderImpl.java:69)
        at org.monarchinitiative.biodownload.BioDownloaderImpl.download(BioDownloaderImpl.java:49)
        at org.monarchinitiative.lirical.cli.cmd.DownloadCommand.execute(DownloadCommand.java:57)
        at org.monarchinitiative.lirical.cli.cmd.BaseCommand.call(BaseCommand.java:31)
        at org.monarchinitiative.lirical.cli.cmd.DownloadCommand.call(DownloadCommand.java:21)
        at org.monarchinitiative.lirical.cli.cmd.BaseCommand.call(BaseCommand.java:18)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.monarchinitiative.lirical.cli.Main.main(Main.java:46)
        
        
I tried it several times in different days, but the error still lasts... please help!

**Comment by ielis** [comment]
Hi @MiladEidi 

Running

```shell
wget https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
```

runs OK on my end, so I do not think there are any issues with the hosting. Your connectivity issues may be a result being behind a firewall (or similar), and, unfortunately, it is impossible for me to help you with that.

As a workaround, you can download the `.ser` files on another machine, and then copy them into the `/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data` folder.

Please have a look [here](https://github.com/TheJacksonLaboratory/LIRICAL/blob/22bf5f2dde0aff2107ac530fe709e275812ad431/lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/DownloadCommand.java#L51), there are 4 URLs that are hosted on Google Cloud storage.

This is how the data folder should look like at the end:
```
data
├── hg19_refseq.ser
├── hg19_ucsc.ser
├── hg38_refseq.ser
├── hg38_ucsc.ser
├── hgnc_complete_set.txt
├── hp.json
├── mim2gene_medgen
└── phenotype.hpoa
```

I'd be happy to help further if the above does not work, please let me know.

**Comment by MiladEidi** [comment]
Thank you bro, but I downloaded the databases somewhere else...
Now I am getting another error as follows:

(base) milad@DESKTOP-VI9DTD8:/mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2$ java -jar lirical-cli-2.0.2.jar R -p=HP:0000821,HP:0000851 --use-orphanet --exomiser-hg38=/mnt/e/NGSneeds/Exomiser/hg38_exomiser/2402_hg38/2402_hg38_variants.mv.db  --vcf=/mnt/c/Users/Milad/OneDrive/Desktop/CH-063-04.hard-filtered.vcf.gz --assembly=hg38 -o=/mnt/c/Users/Milad/OneDrive/Desktop/CH-063-04
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]

  _     ___ ____  ___ ____    _    _
 | |   |_ _|  _ \|_ _/ ___|  / \  | |
 | |    | || |_) || | |     / _ \ | |
 | |___ | ||  _ < | | |___ / ___ \| |___
 |_____|___|_| \_\___\____/_/   \_\_____|

LIkelihood Ratio Interpretation of Clinical AbnormaLities
                                    :: v2.0.2 ::


12:44:37.085 [main] INFO  o.m.l.c.c.LiricalConfigurationCommand - Running LIRICAL from /mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/lirical-cli-2.0.2.jar
12:44:37.092 [main] INFO  o.m.l.c.c.LiricalConfigurationCommand - Using data folder at /mnt/c/Users/Milad/OneDrive/Desktop/lirical-cli-2.0.2/data
12:44:37.093 [main] INFO  o.m.l.c.c.AbstractPrioritizeCommand - Parsing the analysis inputs
12:44:37.096 [main] INFO  o.m.l.c.c.AbstractPrioritizeCommand - Bootstrapping LIRICAL
12:44:38.746 [main] ERROR o.m.l.c.c.AbstractPrioritizeCommand - Error: org.monarchinitiative.phenol.graph.exc.GraphNotSimpleException: Self-loop edge: Relationship [source=HP:0010464, target=HP:0010464, id=9667, relationshipType=RelationshipType{id='is_a', label='is_a'}]

do you where is the problem?

**Comment by MiladEidi** [comment]
I think there is a bug when I want to use LIRICAL with hg38 version of human genome. the Exomiser database I am using is "2402_hg38_variants.mv.db".

Please help...
Best,
Milad

**Comment by ielis** [comment]
Hi @MiladEidi 
this is because LIRICAL does not yet support the latest Exomiser variant database format.

The latest data release supported by LIRICAL is [2309](https://github.com/exomiser/Exomiser/discussions/527).

We plan adding the support for the latest format.

**Comment by MiladEidi** [comment]
uh, thank you bro for the prompt support

**Comment by ielis** [comment]
Hi @MiladEidi 
Just letting you know here that we just released LIRICAL v2.1.0 with support of the latest Exomiser variant database format.

The simplest way to use LIRICAL is pointing to Exomiser's data directory with the novel `-ed19` or `-ed38` CLI options, as described [in the docs](https://thejacksonlaboratory.github.io/LIRICAL/stable/running.html#resources).

If there is anything else we could help with, please let me know.
